import { spawn } from "node:child_process";
import { constants } from "node:fs";
import { access, mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const root = process.cwd();

const argumentsSet = new Set(process.argv.slice(2));

const shouldSkipC = argumentsSet.has("--skip-c") || process.env.SKIP_C_WASM === "1";
const shouldSkipRust = argumentsSet.has("--skip-rust") || process.env.SKIP_RUST_WASM === "1";

const paths = {
  cSourcePath: path.join(root, "c", "optimized-tensor", "optimized_tensor.c"),
  cWasmPath: path.join(root, "c", "optimized-tensor", "target", "optimized_tensor.wasm"),
  cOutputPath: path.join(root, "src", "wasm", "cOptimizedTensor.wasm-bytes.ts"),

  rustManifestPath: path.join(root, "rust", "optimized-tensor", "Cargo.toml"),
  rustWasmPath: path.join(
    root,
    "rust",
    "optimized-tensor",
    "target",
    "wasm32-unknown-unknown",
    "release",
    "optimized_tensor.wasm",
  ),
  rustOutputPath: path.join(root, "src", "wasm", "rustOptimizedTensor.wasm-bytes.ts"),
};

await main();

async function main() {
  console.log("WASM build configuration:");
  console.log(`  skip C: ${shouldSkipC}`);
  console.log(`  skip Rust: ${shouldSkipRust}`);

  if (shouldSkipC) {
    await assertReadableFile(
      paths.cOutputPath,
      "Existing generated C WASM byte module is missing. Run `pnpm build:wasm:c` locally and commit the generated file.",
    );

    console.log(`Reusing existing generated C WASM byte module: ${paths.cOutputPath}`);
  } else {
    await buildCOptimizedTensor();
  }

  if (shouldSkipRust) {
    await assertReadableFile(
      paths.rustOutputPath,
      "Existing generated Rust WASM byte module is missing. Run `pnpm build:wasm:rust` locally and commit the generated file.",
    );

    console.log(`Reusing existing generated Rust WASM byte module: ${paths.rustOutputPath}`);
  } else {
    await buildRustOptimizedTensor();
  }
}

async function buildCOptimizedTensor() {
  await assertReadableFile(paths.cSourcePath, "C source file is missing.");

  await mkdir(path.dirname(paths.cWasmPath), { recursive: true });

  await run("clang", [
    "--target=wasm32-unknown-unknown",
    "-O3",
    "-nostdlib",
    "-Wl,--no-entry",
    "-Wl,--export-memory",
    "-Wl,--export=max_waves",
    "-Wl,--export=amps_ptr",
    "-Wl,--export=freqs_ptr",
    "-Wl,--export=phases_ptr",
    "-Wl,--export=combine",
    "-o",
    paths.cWasmPath,
    paths.cSourcePath,
  ]);

  await writeBytesModule(
    paths.cOutputPath,
    "cOptimizedTensorWasmBytes",
    await readFile(paths.cWasmPath),
  );
}

async function buildRustOptimizedTensor() {
  await assertReadableFile(paths.rustManifestPath, "Rust Cargo manifest is missing.");

  await run("cargo", [
    "build",
    "--release",
    "--target",
    "wasm32-unknown-unknown",
    "--manifest-path",
    paths.rustManifestPath,
  ]);

  await writeBytesModule(
    paths.rustOutputPath,
    "rustOptimizedTensorWasmBytes",
    await readFile(paths.rustWasmPath),
  );
}

async function writeBytesModule(outputPath, exportName, buffer) {
  const bytes = Array.from(buffer);

  const lines = [
    "// Generated by scripts/build-wasm.mjs. Do not edit by hand.",
    `export const ${exportName} = new Uint8Array([`,
  ];

  for (let index = 0; index < bytes.length; index += 16) {
    lines.push(`  ${bytes.slice(index, index + 16).join(", ")},`);
  }

  lines.push("]);", "");

  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, lines.join("\n"), "utf8");

  console.log(`Wrote generated WASM byte module: ${outputPath}`);
}

async function assertReadableFile(filePath, message) {
  try {
    await access(filePath, constants.R_OK);
  } catch {
    throw new Error(`${message}\nPath: ${filePath}`);
  }
}

function run(command, args) {
  return new Promise((resolve, reject) => {
    const child = spawn(command, args, {
      cwd: root,
      stdio: "inherit",
      shell: false,
    });

    child.on("error", (error) => {
      if (error.code === "ENOENT") {
        reject(
          new Error(
            [
              `Required executable was not found: ${command}`,
              "",
              "This usually means the deployment environment does not provide the native toolchain needed by this build step.",
              "",
              command === "clang"
                ? "For Vercel, use `pnpm build:wasm -- --skip-c` and commit `src/wasm/cOptimizedTensor.wasm-bytes.ts`, or compile C WASM in GitHub Actions."
                : "Install the missing executable in CI, or skip this build step if the generated artifact is already committed.",
              "",
              `Original error: ${error.message}`,
            ].join("\n"),
          ),
        );
        return;
      }

      reject(error);
    });

    child.on("exit", (code) => {
      if (code === 0) {
        resolve();
        return;
      }

      reject(new Error(`${command} ${args.join(" ")} failed with exit code ${code}`));
    });
  });
}