import { spawn } from "node:child_process";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const root = process.cwd();

await buildRustOptimizedTensor();

async function buildRustOptimizedTensor() {
  const manifestPath = path.join(root, "rust", "optimized-tensor", "Cargo.toml");
  const wasmPath = path.join(
    root,
    "rust",
    "optimized-tensor",
    "target",
    "wasm32-unknown-unknown",
    "release",
    "optimized_tensor.wasm",
  );
  const outputPath = path.join(root, "src", "wasm", "rustOptimizedTensor.wasm-bytes.ts");

  await run("cargo", [
    "build",
    "--release",
    "--target",
    "wasm32-unknown-unknown",
    "--manifest-path",
    manifestPath,
  ]);

  await writeBytesModule(
    outputPath,
    "rustOptimizedTensorWasmBytes",
    await readFile(wasmPath),
  );
}

async function writeBytesModule(outputPath, exportName, buffer) {
  const bytes = Array.from(buffer);
  const lines = [
    "// Generated by scripts/build-wasm.mjs. Do not edit by hand.",
    `export const ${exportName} = new Uint8Array([`,
  ];

  for (let index = 0; index < bytes.length; index += 16) {
    lines.push(`  ${bytes.slice(index, index + 16).join(", ")},`);
  }

  lines.push("]);", "");

  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, lines.join("\n"), "utf8");
}

function run(command, args) {
  return new Promise((resolve, reject) => {
    const child = spawn(command, args, {
      cwd: root,
      stdio: "inherit",
    });

    child.on("error", reject);
    child.on("exit", (code) => {
      if (code === 0) {
        resolve();
        return;
      }

      reject(new Error(`${command} ${args.join(" ")} failed with exit code ${code}`));
    });
  });
}
