// @generated by rustplus. Do not edit manually.
// Source: C:\Users\timot\code\2026\Rust\Transpiler\SelfDocumenting\rustplus_transpiler(18)\rustplus_transpiler\examples\normal-rust-project\src\main.rp
// rustplus-line-map: approximate
// rustplus-source: C:\Users\timot\code\2026\Rust\Transpiler\SelfDocumenting\rustplus_transpiler(18)\rustplus_transpiler\examples\normal-rust-project\src\main.rp
// rustplus-map: 1->1, 2->2, 3->3, 4->4, 5->5, 6->6, 7->7, 8->8, 9->9, 10->10, 11->11, 12->12, 13->13, 14->14, 15->15, 16->16, ...

mod account;

use account::{Account, IAccount};

fn main() {
    let mut stack_account: Account = Account::new("account-stack".to_string());
    stack_account.deposit(100);

    println!("{}", stack_account.id());
    println!("stack balance = {}", stack_account.balance());

    let mut account: Box<dyn IAccount> = Box::new(Account::new("account-1".to_string()));

    account.deposit(250);
    account.deposit(125);

    println!("{}", account.id());
    println!("balance = {}", account.balance());
}
