set shell := ["powershell.exe", "-NoLogo", "-NoProfile", "-Command"]

default:
    just --list

check:
    @cargo check

test:
    @cargo test

lint:
    @cargo clippy --all-targets -- -D warnings

perf writer_iterations="1000000" stdout_iterations="10000":
    @$env:RUSTFLAGS='-C opt-level=3'; cargo run --release --bin perf_all -- {{writer_iterations}} {{stdout_iterations}} > $null

perf-smoke:
    @$env:RUSTFLAGS='-C opt-level=3'; cargo run --release --bin perf_all -- 1000 10 > $null
