set shell := ["pwsh.exe", "-NoLogo", "-NoProfile", "-Command"]

default:
    just --list

check:
    @cargo check

check-output-stress:
    @cargo check --manifest-path stress_cases/output_stress_case/Cargo.toml

test:
    @cargo test

lint:
    @cargo clippy --all-targets -- -D warnings

perf:
    @$env:RUSTFLAGS='-C opt-level=3'; cargo run --release --bin perf_all -- 1000000 10000 > $null

perf_prop writer_iterations="1000000" stdout_iterations="10000":
    @$env:RUSTFLAGS='-C opt-level=3'; cargo build --release --bin perf_all
    @.\target\release\perf_all.exe {{ writer_iterations }} {{ stdout_iterations }} > $null

perf-smoke:
    @just perf_prop 10000 100

run-output-stress:
    @cargo run --manifest-path stress_cases/output_stress_case/Cargo.toml
