// @generated by rustplus. Do not edit manually.
// Source: C:\Users\timot\code\2026\Rust\Transpiler\better testing\rustplus_transpiler(19)\rustplus_transpiler\examples\normal-rust-project\src\account.rp
// rustplus-line-map: approximate
// rustplus-source: C:\Users\timot\code\2026\Rust\Transpiler\better testing\rustplus_transpiler(19)\rustplus_transpiler\examples\normal-rust-project\src\account.rp
// rustplus-map: 1->1, 2->2, 3->3, 4->4, 5->5, 6->6, 7->7, 8->8, 9->9, 10->10, 11->11, 12->12, 13->13, 14->14, 15->15, 16->16, ...

pub trait IAccount {
    fn id(&self) -> &str;
    fn deposit(&mut self, amount: i64);
    fn balance(&self) -> i64;
}

#[cfg(target_os = "linux")]
pub struct Account {
    id: String,
    balance: i64,
}

impl Account {
    pub fn new(id: String) -> Self {
        return Self { id, balance: 0 };
    }
}

impl IAccount for Account {
    fn id(&self) -> &str {
        return &self.id;
    }

    fn deposit(&mut self, amount: i64) {
        self.balance += amount;
    }

    fn balance(&self) -> i64 {
        return self.balance;
    }
}
