use crate::config::RustPlusConfig;
use crate::incremental::{config_fingerprint, default_cache_path, CacheStats, IncrementalCache};
use crate::line_map::SourceLineMap;
use crate::program::RustPlusProgram;
use crate::project::find_default_config;
use anyhow::{anyhow, Context, Result};
use std::env;
use std::ffi::OsStr;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;
use walkdir::WalkDir;

const GENERATED_MARKER: &str = "// @generated by rustplus";

#[derive(Debug, Clone)]
pub struct CargoBuildOptions {
    pub source_root: PathBuf,
    pub config_path: Option<PathBuf>,
    pub run_rustfmt: bool,
    pub overwrite_non_generated_rs: bool,
    pub emit_cargo_rerun_instructions: bool,
    pub use_incremental_cache: bool,
    pub emit_line_maps: bool,
}

impl CargoBuildOptions {
    pub fn new(source_root: impl Into<PathBuf>) -> Self {
        return Self {
            source_root: source_root.into(),
            config_path: None,
            run_rustfmt: true,
            overwrite_non_generated_rs: false,
            emit_cargo_rerun_instructions: true,
            use_incremental_cache: true,
            emit_line_maps: true,
        };
    }

    pub fn with_config_path(mut self, config_path: impl Into<PathBuf>) -> Self {
        self.config_path = Some(config_path.into());
        return self;
    }

    pub fn without_rustfmt(mut self) -> Self {
        self.run_rustfmt = false;
        return self;
    }

    pub fn overwrite_non_generated_rs(mut self, enabled: bool) -> Self {
        self.overwrite_non_generated_rs = enabled;
        return self;
    }

    pub fn emit_cargo_rerun_instructions(mut self, enabled: bool) -> Self {
        self.emit_cargo_rerun_instructions = enabled;
        return self;
    }

    pub fn use_incremental_cache(mut self, enabled: bool) -> Self {
        self.use_incremental_cache = enabled;
        return self;
    }

    pub fn emit_line_maps(mut self, enabled: bool) -> Self {
        self.emit_line_maps = enabled;
        return self;
    }
}

pub fn compile_sibling_files(source_root: impl AsRef<Path>) -> Result<()> {
    let options = CargoBuildOptions::new(source_root.as_ref().to_path_buf());
    return compile_sibling_files_with_options(options).map(|_| ());
}

pub fn compile_sibling_files_with_options(options: CargoBuildOptions) -> Result<CacheStats> {
    let manifest_dir = env::var_os("CARGO_MANIFEST_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("."));

    let source_root = absolutize_from_manifest(&manifest_dir, &options.source_root);

    if !source_root.exists() {
        return Err(anyhow!("Rust Plus source root does not exist: {}", source_root.display()));
    }

    if !source_root.is_dir() {
        return Err(anyhow!("Rust Plus source root is not a directory: {}", source_root.display()));
    }

    let config_path = options
        .config_path
        .as_ref()
        .map(|path| absolutize_from_manifest(&manifest_dir, path))
        .or_else(|| find_default_config(&source_root));

    let config = RustPlusConfig::load_optional(config_path.as_deref())?;
    let config_hash = config_fingerprint(&config);
    let rustfmt_available = options.run_rustfmt && is_rustfmt_available();
    let cache_path = default_cache_path(&manifest_dir);
    let mut cache = if options.use_incremental_cache {
        IncrementalCache::load(&cache_path)?
    } else {
        IncrementalCache::default()
    };
    let mut cache_stats = CacheStats::default();

    if options.emit_cargo_rerun_instructions {
        println!("cargo:rerun-if-changed={}", source_root.display());

        if let Some(path) = &config_path {
            println!("cargo:rerun-if-changed={}", path.display());
        }
    }

    let mut rp_files = collect_rp_files(&source_root)?;
    rp_files.sort();

    let mut rp_sources = Vec::with_capacity(rp_files.len());

    for input_path in rp_files {
        if options.emit_cargo_rerun_instructions {
            println!("cargo:rerun-if-changed={}", input_path.display());
        }

        let source = fs::read_to_string(&input_path)
            .with_context(|| format!("failed to read {}", input_path.display()))?;
        rp_sources.push((input_path, source));
    }

    let mut program = RustPlusProgram::from_named_sources(rp_sources.clone(), config.clone())?;

    for (index, (input_path, source)) in rp_sources.iter().enumerate() {
        let mut output_path = input_path.clone();
        output_path.set_extension("rs");

        if options.use_incremental_cache && cache.is_fresh(input_path, &output_path, source, &config_hash) {
            cache_stats.hits += 1;
            continue;
        }

        cache_stats.misses += 1;
        let emit_output = program.emit_file(index, Some(output_path.clone()))?;
        let mut generated = format_generated_file(input_path, &emit_output.rust, Some(&emit_output.line_map));

        if rustfmt_available {
            generated = format_generated_with_rustfmt(&output_path, &generated)?;
        }

        write_generated_file(&output_path, &generated, options.overwrite_non_generated_rs)?;

        if options.emit_line_maps {
            let map_path = line_map_path_for(&output_path);
            emit_output
                .line_map
                .write_sidecar(&map_path)
                .with_context(|| format!("failed to write line map {}", map_path.display()))?;
        }

        cache.update(input_path, &output_path, source, &generated, &config_hash);
        cache_stats.writes += 1;
    }

    if options.use_incremental_cache {
        cache.save(&cache_path)?;
    }

    if options.emit_cargo_rerun_instructions {
        println!(
            "cargo:warning=rustplus cache: {} hit(s), {} miss(es), {} write(s)",
            cache_stats.hits, cache_stats.misses, cache_stats.writes
        );
    }

    return Ok(cache_stats);
}

fn write_generated_file(output_path: &Path, generated: &str, overwrite_non_generated_rs: bool) -> Result<()> {
    if output_path.exists() {
        let existing = fs::read_to_string(output_path)
            .with_context(|| format!("failed to read existing generated target {}", output_path.display()))?;

        if existing == generated {
            return Ok(());
        }

        if !overwrite_non_generated_rs && !existing.starts_with(GENERATED_MARKER) {
            return Err(anyhow!(
                "refusing to overwrite non-generated Rust file: {}. Delete it, rename it, or call overwrite_non_generated_rs(true).",
                output_path.display()
            ));
        }
    }

    if let Some(parent) = output_path.parent() {
        fs::create_dir_all(parent).with_context(|| format!("failed to create {}", parent.display()))?;
    }

    fs::write(output_path, generated).with_context(|| format!("failed to write {}", output_path.display()))?;
    return Ok(());
}

fn format_generated_with_rustfmt(output_path: &Path, generated: &str) -> Result<String> {
    let file_name = output_path
        .file_name()
        .and_then(OsStr::to_str)
        .unwrap_or("generated.rs");
    let temp_file_name = format!(".{}.rustplus.tmp.rs", file_name);
    let temp_path = output_path.with_file_name(temp_file_name);

    fs::write(&temp_path, generated)
        .with_context(|| format!("failed to write temporary rustfmt file {}", temp_path.display()))?;

    let format_result = run_rustfmt(&temp_path);

    if let Err(error) = format_result {
        let _ = fs::remove_file(&temp_path);
        return Err(error);
    }

    let formatted = fs::read_to_string(&temp_path)
        .with_context(|| format!("failed to read temporary rustfmt file {}", temp_path.display()))?;
    let _ = fs::remove_file(&temp_path);

    return Ok(formatted);
}

fn format_generated_file(input_path: &Path, generated_body: &str, line_map: Option<&SourceLineMap>) -> String {
    let source_path = input_path.display().to_string();
    let generated_body = generated_body.trim();
    let line_map_comment = line_map
        .map(SourceLineMap::render_compact_comment)
        .unwrap_or_default();
    let mut output = String::with_capacity(
        GENERATED_MARKER.len() + source_path.len() + generated_body.len() + line_map_comment.len() + 96,
    );

    output.push_str(GENERATED_MARKER);
    output.push_str(". Do not edit manually.\n");
    output.push_str("// Source: ");
    output.push_str(&source_path);
    output.push('\n');
    output.push_str(&line_map_comment);
    output.push('\n');
    output.push_str(generated_body);
    output.push('\n');
    return output;
}

fn line_map_path_for(output_path: &Path) -> PathBuf {
    let mut path = output_path.to_path_buf();
    path.set_extension("rs.rpmap");
    return path;
}

fn collect_rp_files(source_root: &Path) -> Result<Vec<PathBuf>> {
    let mut files = Vec::new();

    for entry in WalkDir::new(source_root).into_iter() {
        let entry = entry.with_context(|| format!("failed to walk {}", source_root.display()))?;
        let path = entry.path();

        if path.is_file() && path.extension() == Some(OsStr::new("rp")) {
            files.push(path.to_path_buf());
        }
    }

    return Ok(files);
}

fn absolutize_from_manifest(manifest_dir: &Path, path: &Path) -> PathBuf {
    if path.is_absolute() {
        return path.to_path_buf();
    }

    return manifest_dir.join(path);
}

fn is_rustfmt_available() -> bool {
    return Command::new("rustfmt").arg("--version").output().is_ok();
}

fn run_rustfmt(path: &Path) -> Result<()> {
    let status = Command::new("rustfmt")
        .arg(path)
        .status()
        .with_context(|| format!("failed to execute rustfmt for {}", path.display()))?;

    if !status.success() {
        return Err(anyhow!("rustfmt failed for {}", path.display()));
    }

    return Ok(());
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_file_starts_with_marker() {
        let line_map = SourceLineMap::approximate_identity(
            Some(PathBuf::from("src/account.rp")),
            Some(PathBuf::from("src/account.rs")),
            "class Account {}",
            "struct Account\n{\n}\n",
        );
        let generated = format_generated_file(Path::new("src/account.rp"), "struct Account\n{\n}\n", Some(&line_map));

        assert!(generated.starts_with(GENERATED_MARKER));
        assert!(generated.contains("Source: src/account.rp"));
        assert!(generated.contains("rustplus-line-map"));
        assert!(generated.contains("struct Account"));
    }
}
