unstable_features = true

brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"

edition = "2024"
max_width = 200
tab_spaces = 4
hard_tabs = false

imports_granularity = "Preserve"
group_imports = "Preserve"

reorder_imports = true
reorder_modules = true

fn_single_line = false
empty_item_single_line = false
where_single_line = false
