# Convenience commands for the xmake workflow.
set dotenv-load
set shell := ["pwsh.exe", "-NoLogo", "-Command"]
set quiet

_default:
    just --list --unsorted
    #just --summary
    #just --list
format:
    cargo +nightly fmt --all
