// @generated by rustplus. Do not edit manually.
// Source: src/account.rp

pub trait IAccount {
    fn id(&self) -> &str;
    fn deposit(&mut self, amount: i64);
    fn balance(&self) -> i64;
}

pub struct Account {
    id: String,
    balance: i64,
}

impl Account {
    pub fn new(id: String) -> Self {
        return Self { id, balance: 0 };
    }
}

impl IAccount for Account {
    fn id(&self) -> &str {
        return &self.id;
    }

    fn deposit(&mut self, amount: i64) {
        self.balance += amount;
    }

    fn balance(&self) -> i64 {
        return self.balance;
    }
}
