// @generated by rustplus. Do not edit manually.
// Source: src/main.rp

mod account;

use account::{Account, IAccount};

fn main() {
    let mut stack_account: Account = Account::new("account-stack".to_string());
    stack_account.deposit(100);

    println!("{}", stack_account.id());
    println!("stack balance = {}", stack_account.balance());

    let mut account: Box<dyn IAccount> = Box::new(Account::new("account-1".to_string()));

    account.deposit(250);
    account.deposit(125);

    println!("{}", account.id());
    println!("balance = {}", account.balance());
}
